#!/bin/sh
result=$(ping -c 1 8.8.8.8 | awk -F'time=' '/time=/ {print $2}' | awk '{print $1 "ₘₛ"}');
status=$(nmcli -t -f STATE g)
if [ "$status" = "connected" ]; then
    echo "  $result"
else
    echo "❌"
#    echo "󰤮"
fi
