#!/bin/sh
# Requiere: jq y niri

get_workspaces() {
    # niri msg -j workspaces obtiene la info
    # Añadimos | sort_by(.id) para que el orden sea siempre ascendente
    niri msg -j workspaces | jq -c '
        sort_by(.id) |
        map({
            id: .id,
            is_active: .is_focused,
            output: .output
        })'
}

# Envía el estado inicial
get_workspaces

# Escucha eventos de Niri para actualizar al instante
niri msg event-stream | while read -r line; do
    get_workspaces
done
